### ISSUE TITLE
Rfid module

### ISSUE THREAD

**Issue by thostie2002** [esphome/feature-requests#262] opened 2019-06-02 11:58 UTC
**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

I like to have an intergration for this rfid reader, 

https://www.velleman.eu/products/view/?id=435568

**Comment by OttoWinter** [comment] 2019-06-02 12:08
Duplicate of https://github.com/esphome/feature-requests/issues/37

**Closed by OttoWinter** 2019-06-02 12:08 UTC
