### ISSUE TITLE
Add W5xxx Ethernet to PICOW framework

### ISSUE THREAD

**Issue by VAVorontsov** [esphome/feature-requests#2888] opened 2024-09-18 14:23 UTC
**Describe the problem you have/What new integration you would like**

Add W5500 ethernet to raspberry pi pico core

**Please describe your use case for this integration and alternatives you've tried:**

Add W5500 ethernet to raspberry pi pico core

**Please describe your use case for this integration and alternatives you've tried:**
When I tried building a yaml config with the W5500 Ethernet component, the system told me that it was only available on the ESP32 framework. This is odd, as it may even be the same standard Ethernet library that most Arduino cores use. I have built boards with the pico and w5xxx controllers before and they certainly handle them fine. I know this is an ESP focused project, but would be nice to have similar options for the rp2040 boards. 

**Additional context**

**Comment by randybb** [comment] 2024-09-18 14:53
Duplicate of https://github.com/esphome/feature-requests/issues/2802

**Closed by randybb** 2024-09-18 14:53 UTC
