### ISSUE TITLE
Could Modbus Component support  rs485 modbus to tcp network module or server?

### ISSUE THREAD

**Issue by 645340633** [esphome/feature-requests#2208] opened 2023-04-17 02:02 UTC
**Describe the problem you have/What new integration you would like**

Could Modbus Component support connect modbus tcp server? 
I have a rs485 modbus to tcp network server, but the esphome modbus component  only support uart module,so if it could support rs485 modbus to tcp network module or server?
**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by makuser** [comment] 2023-10-05 14:45
Are you asking for ESPHome to act as a Modbus TCP server for other Modbus TCP Clients to be able to connect to or are you asking for ESPHome to connect to another Modbus TCP server as a Modbus TCP client?

I understood your request to be able to connect to the Modbus TCP server you already seem to have, as a Modbus TCP client, which for obvious reasons can not be done over the only currently implemented physical protocol Modbus RTU by a RS485 Transceiver connected via UART.
If so, this is a duplicate of  #1992, but https://github.com/esphome/esphome/pull/4874 would do nothing for you. I have really no idea, why https://github.com/esphome/esphome/pull/4874 marked this FR as being solved by it...

If against all odds do you want ESPHome to act as a Modbus TCP Server and for example either talk Modbus RTU via UART or instead also provide your own registers via a lambda call or so, then https://github.com/esphome/esphome/pull/4874 would indeed implement this.
But in that case, this FR is a duplicate of #708.

Either way, for both Modbus TCP Server or Client, FRs already exist and this one is a duplicate.

**Comment by 645340633** [comment] 2023-10-05 15:36
I mean if it could be like&nbsp; modbus integration of homeassistant.&nbsp; There are lots of differences between esphome&nbsp; module and homeassistant integration. so I hope esphome cloud add the tcp protocol for the modbus module.



---Original---
From: "Marc ***@***.***&gt;
Date: Thu, Oct 5, 2023 22:46 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [esphome/feature-requests] Could Modbus Component support  rs485modbus to tcp network module or server? (Issue #2208)




 
Are you asking for ESPHome to act as a Modbus TCP server for other Modbus TCP Clients to be able to connect to or are you asking for ESPHome to connect to another Modbus TCP server as a Modbus TCP client?
 
I understood your request to be able to connect to the Modbus TCP server you already seem to have, as a Modbus TCP client, which for obvious reasons can not be done over the only currently implemented physical protocol Modbus RTU by a RS485 Transceiver connected via UART.
 If so, this is a duplicate of  #1992, but esphome/esphome#4874 would do nothing for you. I have really no idea, why esphome/esphome#4874 marked this FR as being solved by it...
 
If against all odds do you want ESPHome to act as a Modbus TCP Server and for example either talk Modbus RTU via UART or instead also provide your own registers via a lambda call or so, then esphome/esphome#4874 would indeed implement this.
 But in that case, this FR is a duplicate of #708.
 
Either way, for both Modbus TCP Server or Client, FRs already exist and this one is a duplicate.

**Comment by makuser** [comment] 2023-10-05 16:09
> I mean if it could be like&nbsp; modbus integration of homeassistant.&nbsp; There are lots of differences between esphome&nbsp; module and homeassistant integration. so I hope esphome cloud add the tcp protocol for the modbus module.

So you are looking for a Modbus TCP client functionality. Then I suggest following #1992.

This is a duplicate of #1992, please close this issue.

**Comment by nagyrobi** [comment] 2023-10-06 19:21
Duplicate of https://github.com/esphome/feature-requests/issues/1992

**Closed by nagyrobi** 2023-10-06 19:21 UTC
