### ISSUE TITLE
Support for mqtt payload 0/1 for off/on

### ISSUE THREAD

**Issue by the-butterfry** [esphome/feature-requests#254] opened 2019-05-30 03:42 UTC
**Describe the problem you have/What new integration you would like**

Support for 0 off 1 on payloads on MQTT switches
**Please describe your use case for this integration and alternatives you've tried:**

I have a an application that can only send 0 or 1
**Additional context**

**Comment by OttoWinter** [comment] 2019-05-30 07:34
Duplicate of https://github.com/esphome/feature-requests/issues/187

**Closed by OttoWinter** 2019-05-30 07:34 UTC
Labels: component: binary_sensor, component: mqtt
