### ISSUE TITLE
Possibilities of adding MAX31856

### ISSUE THREAD

**Issue by medicshort87** [esphome/feature-requests#39] opened 2018-08-14 17:52 UTC
Was curious about how to add an spi temp sensor. The max31856 specifically. Dual options would be great since I believe you can combine miso, mosi, and clk and just assign a separate cs pin. 
Heres the link to the libraries. 

Adafruit main library:
https://github.com/adafruit/Adafruit_MAX31856

Library for single, dual, and quad:
https://github.com/engineertype/MAX31856

**Comment by OttoWinter** [comment] 2019-03-24 15:59
Duplicate of https://github.com/esphome/feature-requests/issues/4

**Closed by OttoWinter** 2019-03-24 15:59 UTC
