### ISSUE TITLE
Can I use hardware switches or buttons to control the opening and closing of WiFi.

### ISSUE THREAD

**Issue by cmsjin** [esphome/feature-requests#2188] opened 2023-03-31 07:06 UTC
Can I use hardware switches or buttons to control the opening and closing of WiFi.

**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by ssieb** [comment] 2023-03-31 07:15
Duplicate of https://github.com/esphome/feature-requests/issues/1310
Also, https://github.com/esphome/esphome/pull/1249

**Closed by ssieb** 2023-03-31 07:15 UTC
