### ISSUE TITLE
Allow disabling of the `update_interval:` feature in the LCD display.

### ISSUE THREAD

**Issue by rarroyo6** [esphome/feature-requests#2356] opened 2023-08-16 23:09 UTC
**Describe the problem you have/What new integration you would like**

Be able to optionally disable the `update_interval:` feature on the LCD display.
**Please describe your use case for this integration and alternatives you've tried:**

The `lambda:` on the LCD display gets executed every `update_interval:`, which defaults to 1s.
When the LCD is being used to display slow changing data, like sensor data, it would be beneficial to disable the auto update feature, and only update when the sensor changes, using the `component.update:`
**Additional context**

**Comment by ssieb** [comment] 2023-08-17 00:25
Why did you create another one?  I already answered it.
Duplicate of https://github.com/esphome/feature-requests/issues/2354

**Closed by ssieb** 2023-08-17 00:25 UTC
