### ISSUE TITLE
Wiegand proximity card readers

### ISSUE THREAD

**Issue by sargus123** [esphome/feature-requests#1243] opened 2021-05-31 07:41 UTC
**Describe the problem you have/What new integration you would like**

 Wiegand proximity card readers  - access system to protected zones.

**Please describe your use case for this integration and alternatives you've tried:**

Access control systems use this protocol to transmit information from proximity card readers and keypads.
the advantage of this is that these devices are already in professional housings compared to universal readers for the arduino platform.

**Additional context**

I have bet on: esp d1 mini
program: https://github.com/esprfid/esp-rfid
but there is a problem with wi-fi communication and there is no connection to the Home Assistant.

**Comment by Gio-dot** [comment] 2021-05-31 10:41
There is already a very old request for this:
https://github.com/esphome/feature-requests/issues/211

In Esphome development version it is already working

**Comment by nagyrobi** [comment] 2022-07-07 10:22
Duplicate of https://github.com/esphome/feature-requests/issues/211

**Closed by nagyrobi** 2022-07-07 10:22 UTC
