### ISSUE TITLE
Will it support esp now protocol?

### ISSUE THREAD

**Issue by ChristianSwift** [esphome/feature-requests#1745] opened 2022-05-27 09:01 UTC
**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

espressif already release a protocal called [esp now](https://www.espressif.com/en/products/software/esp-now/overview), it can transmit data between two or more esp chips fast and efficiency, i hope esphome could make it.

**Comment by SeByDocKy** [comment] 2022-06-09 09:24
I saw somewhere an attempt to integrate ESPnow into ESPhome but .... seems in stand by seems several weeks.

**Comment by nagyrobi** [comment] 2022-07-07 08:26
Duplicate of https://github.com/esphome/feature-requests/issues/275

**Closed by nagyrobi** 2022-07-07 08:26 UTC
Labels: enhancement, Type: Communication Channel
