### ISSUE TITLE
PJON over RS485 transceiver

### ISSUE THREAD

**Issue by Kralg** [esphome/feature-requests#1288] opened 2021-07-01 14:13 UTC
**Describe the problem you have/What new integration you would like**

I would like to use PJON over RS485 transceiver on ESP32cam

**Please describe your use case for this integration and alternatives you've tried:**

It would be very nice to use PJON as it supports multi-master communicate over RS485 wired network.

**Additional context**

I would like to know if this is supported in the current version and is there a way to combine this library in the current esphome.
I would like to test this implementation https://github.com/gioblu/PJON/tree/master/examples/ARDUINO/Local/ThroughSerial/RS485-BlinkWithResponse/Receiver

**Comment by nagyrobi** [comment] 2022-07-08 11:52
Duplicate of https://github.com/esphome/feature-requests/issues/1655

**Closed by nagyrobi** 2022-07-08 11:52 UTC
Labels: Type: Communication Channel
