### ISSUE TITLE
REST api for camera

### ISSUE THREAD

**Issue by continuoushealth** [esphome/feature-requests#264] opened 2019-06-02 16:24 UTC
**Describe the problem you have/What new integration you would like**
I would like to use the REST api, to take pictures and possibly make videos without using Home-Assistant.

**Please describe your use case for this integration and alternatives you've tried:**

It appears not possible to take pictures remotely via the REST api.

**Additional context**

**Comment by OttoWinter** [comment] 2019-06-03 07:33
Kind of a duplicate of https://github.com/esphome/feature-requests/issues/205 - will close for the same reasons.

**Closed by OttoWinter** 2019-06-03 07:33 UTC
Labels: component: esp32_camera
