### ISSUE TITLE
Keypad 

### ISSUE THREAD

**Issue by thostie2002** [esphome/feature-requests#263] opened 2019-06-02 14:17 UTC
**Describe the problem you have/What new integration you would like**

An intergration for a keypad 3x4 or 4x4 

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by OttoWinter** [comment] 2019-06-02 14:27
Duplicate of https://github.com/esphome/feature-requests/issues/31

**Closed by OttoWinter** 2019-06-02 14:27 UTC
