### ISSUE TITLE
I2C EEPROM support to does not burn flash for storing state variables

### ISSUE THREAD

**Issue by mrkvo** [esphome/feature-requests#2032] opened 2022-12-22 21:52 UTC
**Describe the problem you have/What new integration you would like**
I would like to suggest make a new component, I2C eeprom like 24C01, 24C02 etc.. for storing variables over reboot (switches status, etc.)

Just define 24Cxx eeprom and let esphome know that he can store state variables there.

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by nagyrobi** [comment] 2022-12-23 08:07
Duplicate of https://github.com/esphome/feature-requests/issues/776

**Closed by nagyrobi** 2022-12-23 08:07 UTC
