### ISSUE TITLE
Can't trigger automations based on output and/or light states changes in HA

### ISSUE THREAD

**Issue by theone11** [esphome/feature-requests#706] opened 2020-04-28 16:11 UTC
**Describe the problem you have/What new integration you would like**
I have a light switch (generic tuya WF-WS01) with a button, led, relay.
I defined then using:
- binary_sensor/gpio (button)
- switch/gpio (led)
- output/gpio + light/binary (relay)

I want to change the led state based on the output/light state if it changes in HA.

**Please describe your use case for this integration and alternatives you've tried:**
My problem is that if I change the light status in HA I have no way of changing the led state in the device.
Light, Output do not have triggers for automation not do they have a "state" to use in lambdas.

**Additional context**
https://community.home-assistant.io/t/controlling-led-switch-after-activaltion-of-light-from-ha/190765

**Comment by glmnet** [comment] 2020-04-28 19:27
duplicate of #98 also fixed in https://github.com/esphome/esphome/pull/1037

**Closed by glmnet** 2020-04-28 19:27 UTC
