### ISSUE TITLE
API over serial

### ISSUE THREAD

**Issue by thompsa** [esphome/feature-requests#111] opened 2019-03-17 09:05 UTC
**Describe the problem you have/What new integration you would like**

For sensors outside wifi range it would be good to be able to link an ESPHome device to Home Assistant over serial. Options for the remote communication include XBee and LoRa. The API seems to be stream based over a single TCP connection so is serial-like. Home Assistant would need to discover/chat via a uart.

**Please describe your use case for this integration and alternatives you've tried:**

Bring the simplicity of ESPHome DIY Home Automation to remote sites where wifi connectivity is not possible due to distance or terrain. 

**Additional context**

**Comment by OttoWinter** [comment] 2019-03-17 09:25
Duplicate of https://github.com/esphome/feature-requests/issues/27

Serial is close to TCP, but it lacks an important concept: A "connection" that can be opened/closed.

**Closed by OttoWinter** 2019-03-17 09:25 UTC
