### ISSUE TITLE
add ser2net component

### ISSUE THREAD

**Issue by dodojie** [esphome/feature-requests#638] opened 2020-03-14 15:29 UTC
**Describe the problem you have/What new integration you would like**

Transmit serial port data to tcp
**Please describe your use case for this integration and alternatives you've tried:**

ser2net of esp8266
**Additional context**

[Serial2Net_ESP8266](https://github.com/soif/Serial2Net_ESP8266)

**Comment by dodojie** [comment] 2020-03-14 15:32
I want to be a gateway（zigbee） on the cc2531.

**Comment by randybb** [comment] 2020-03-14 21:49
No. https://github.com/esphome/feature-requests/issues/415
The main purpose of ESPHome is to interact with HA. If you need bridging or any other special functionalities you can chose from million other projects.

**Comment by glmnet** [comment] 2020-04-17 12:29
Duplicate of #660

**Closed by glmnet** 2020-04-17 12:29 UTC
