### ISSUE TITLE
BSEC library for BME680

### ISSUE THREAD

**Issue by gaiar** [esphome/feature-requests#329] opened 2019-07-16 15:18 UTC
**Describe the problem you have/What new integration you would like**

BME680 can provide actual Indoor Air Quality (IAQ) score, but that data can be pulled only via closed-source Bosch library called BSEC. Bosch supporting Arduino and ESP* for these libraries. Example of BSEC library usage can be found here: https://github.com/alexh-name/bsec_bme680_linux. Maybe it would be possible to include that library in ESPHome builds.

**Please describe your use case for this integration and alternatives you've tried:**

Getting IAQ score data via ESPHome.

**Additional context**

https://github.com/weiqing-beijing/espressif_esp32_esp8266_samples/tree/master/eps32_bme680_iaq_output_pio_succeed

**Comment by OttoWinter** [comment] 2019-10-19 21:05
Duplicate of https://github.com/esphome/feature-requests/issues/16

BSEC is closed-source and cannot be added to ESPHome because of its license.

**Closed by OttoWinter** 2019-10-19 21:05 UTC
