### ISSUE TITLE
Support for Pi Pico 2W (RP2350)

### ISSUE THREAD

**Issue by danielkent-net** [esphome/feature-requests#2959] opened 2024-11-26 19:20 UTC
**Describe the problem you have/What new integration you would like**
The newly released Raspberry Pi Pico 2W (RP2350) should be supported in esphome, given the improved performance, reduced power usage, and the inclusion of new RISC cores that will be useful to some users, if those are possible to use instead of the ARM cores.

**Please describe your use case for this integration and alternatives you've tried:**
The rpipico integration with the RP2040-based Pico W will still work fine, but users might prefer the RP2350 based Pico 2W for performance and feature reasons. Additionally, there may come a time when the RP2040 reaches end of life, so having a newer variant supported will help future proof current Pico-based designs.

**Additional context**
I have ordered three RPi Pico 2Ws for testing which I plan to use to help with testing and troubleshooting. I will hopefully receive them sometime next week; if anyone gets a 2W sooner and would like to start testing, please feel free to contribute.

There is already support for the RP2350 in [Max Gerhard's repository](https://github.com/maxgerhardt/platform-raspberrypi/issues/69), which will likely be what esphome should use for support given the mainline PlatformIO support issues with RPi Pico boards. I'm not sure if this will work for the 2W specifically, but I'm willing to test it out. I'll add any related issues from Max's repo here.

I'm not sure at this stage what support for selecting RISC cores instead of ARM cores would look like, if it can be supported at all. It could be done under a separate board:
```
rp2350:
  board: pipico2w-risc
```
Or perhaps as an option unique to the `rp2350` platform:
```
rp2350:
  board: pipico2w
  coretype: risc  
```
Of course, esphome would need to be able to compile for the RP2350 RISC cores at all before considering the YAML/frontend components. Hopefully that won't be too hard to test.

**Comment by randybb** [comment] 2024-11-26 20:28
Duplicate of #2837

**Closed by randybb** 2024-11-26 20:28 UTC
