### ISSUE TITLE
Use an ESP to flash/adopt other ESPs

### ISSUE THREAD

**Issue by dala318** [esphome/feature-requests#2283] opened 2023-06-22 20:02 UTC
**Describe the problem you have/What new integration you would like**

Add a "flasher" component that can be deployed on a generic ESP. You then can use this ESP to connect to other ESP via UART and as soon as it detects another non-ESPHome device communicating on the UART it deploys a bare firmware in that device that then pops up in your dashboard.

**Please describe your use case for this integration and alternatives you've tried:**

Would be handy to flash say Sonoff devices installed around your house but don't want to move around your PC and USB flashing cables.

Could likely be solved by a stream_server on an ESP and virtual COM on the PC that then thinks it's connected directly to the ESP. But an automated solution would be much appreciated.

**Additional context**

Possible extended features:
 - Binary sensor that tells if UART has connection
 - Binary sensor that tells if the connected device is flashed
 - Button to start flashing
 - Switch for "auto-flash"

**Comment by Mat931** [comment] 2023-06-25 21:03
Possible duplicate of https://github.com/esphome/feature-requests/issues/2242

**Closed** 2023-06-26 05:00 UTC
