### ISSUE TITLE
Add General PID Controller Component to ESPHome

### ISSUE THREAD

**Issue by bzumik1** [esphome/feature-requests#2775] opened 2024-06-21 21:43 UTC
**Describe the problem you have/What new integration you would like**
I would like to have a general PID controller component added to ESPHome. This PID controller should be flexible and usable with various inputs and outputs, similar to the PID Climate component but not restricted to specific applications.

**Please describe your use case for this integration and alternatives you've tried:**
I need a PID controller to manage a ventilation system based on CO2 levels. The PID Climate component is too specific and cannot be used for general PID control applications. Custom lambda function solutions are complex and unreliable.

**Additional context**
PID control is a universal method with wide application potential in various ESPHome automation projects. Adding this component would significantly simplify the implementation of complex control algorithms.

**Comment by nagyrobi** [comment] 2024-06-21 22:05
Duplicate of https://github.com/esphome/feature-requests/issues/1871

**Closed by nagyrobi** 2024-06-21 22:05 UTC
