### ISSUE TITLE
BLE irrigation timer

### ISSUE THREAD

**Issue by kerimt-dek** [esphome/feature-requests#524] opened 2019-12-11 00:03 UTC
**Describe the problem you have/What new integration you would like**

I have several of Holman BTX1 bluetooth tap timers installed in my garden. 

https://www.bunnings.com.au/holman-btx1-bluetooth-smart-valve-1-station_p0011576?gclid=CjwKCAiAob3vBRAUEiwAIbs5Tsh7p03sUhhha9Bg7F9a7mMGkDIp8JjXM9LfaamXkwJZacsKOzhvqBoCAsEQAvD_BwE&gclsrc=aw.ds

They are programmed by iOS app, such that at specific time of the day tap timer is turned on and runs for specific time. I would like to control these devices by ESPHome and HA, such that irrigation is based on weather condition.

**Please describe your use case for this integration and alternatives you've tried:**

Using "lightblue" BLE app on my phone or computer I can connect to each of these devices, read services and characteristics available etc.

I figured out how to turn on watering for specific period by writing characteristic, also using Lightblue. This would be very useful on a hot day, to top up watering in addition to regular watering intervals already programmed.

I would like to use esp32 as esphome device, such that irrigation can be controlled from HA, based on weather condition etc. and also to enable longer range where esphome also acts as WiFi-BLE repeater.

**Additional context**

I would like to see esphome feature where generic BLE sensor can be added and allows esphome to read and write characteristics selected by MAC address and service UUID.

**Comment by brandond** [comment] 2019-12-11 01:32
Duplicate of https://github.com/esphome/feature-requests/issues/485#issuecomment-561586842

**Closed** 2019-12-11 01:32 UTC
