### ISSUE TITLE
OMRON D6T Series (D6T-1A-02)

### ISSUE THREAD

**Issue by ngreis** [esphome/feature-requests#252] opened 2019-05-29 16:46 UTC
**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

For a better integration of humam presence in a room, instead of a PIR sensor the OMRON D6T is a good choice, or the thermal technologie is a good choice.
It uses I2C, it is relatively cheap (some of then at least), it would be a good integration to do.
This is a first choice sensor for this job, so support for it would be very good for the community

Best regards

**Comment by OttoWinter** [comment] 2019-05-29 16:52
Duplicate of https://github.com/esphome/feature-requests/issues/178

**Closed by OttoWinter** 2019-05-29 16:52 UTC
