### ISSUE TITLE
Add Media Player integration to ESPHome

### ISSUE THREAD

**Issue by rarroyo6** [esphome/feature-requests#1075] opened 2021-01-07 00:00 UTC
**Describe the problem you have/What new integration you would like**

Add the Media Player integration into ESPHome.
The ESP might not be powerful enough to support full media playback, but it can be used to switch relays which in turn can control old or "dumb" receivers, or it can receive action signals from HA and generate IR signals to control a receiver which might not be directly supported by HA.
It would also allow ESPHome to be used for Text to Speech by HA.

**Please describe your use case for this integration and alternatives you've tried:**

It would allow using an "Old" receiver/CD player/Tape deck (yes there are still some of these around), which have remote control, but they can't be directly controlled by HA. You can go around it by creating an automation to send IR codes, but it would be nice if HA would recognize and treat them as a media device, and have the ESP send all the proper signals to perform the actions requested by HA.

**Additional context**

HA could also use it to play TTS. The ESP is powerful enough to receive a link to a MP3 file, open the file, and send it to a MP3 decoder module, such as the VS1053, for processing.

**Comment by KTibow** [comment] 2021-01-10 02:16
In the meantime, couldn't you use a template media player?

**Comment by rarroyo6** [comment] 2021-01-12 05:00
> 
> 
> In the meantime, couldn't you use a template media player?

I do not see a media player template in the ESPHome integrations. Am I missing something?

**Comment by KTibow** [comment] 2021-01-12 14:50
I mean in HA. Expose a custom service or template switches to HA, and use this:
https://github.com/Sennevds/media_player.template

**Comment by kquinsland** [comment] 2021-02-17 17:37
This appears to be a duplicate of https://github.com/esphome/feature-requests/issues/783

**Comment by KTibow** [comment] 2021-02-17 17:51
That one is older; however this one has more attention (judging by 5 👍s here and 3 ❤️s there)

**Comment by wjbuys** [comment] 2021-11-29 20:07
For an idea of the scope of work needed for this, here's everything that needed to change to add a new Button component and wire it up all the way through the API into Home Assistant:

- https://github.com/esphome/esphome/pull/2824
- https://github.com/esphome/aioesphomeapi/pull/143
- https://github.com/home-assistant/core/pull/60522

**Comment by kquinsland** [comment] 2021-11-29 21:30
@wjbuys Thanks for that. I'd like to point out something that's easy to miss: that's the scope of work required for ESPHome <-> HA via the HA API.  The steps would be a bit different if you wanted to do this purely via MQTT. 

At a minimum, I am not aware of HA supporting a media-player via MQTT / there does not appear to be a way for an entity to announce it'sself to HA via MQTT.

**Comment by rarroyo6** [comment] 2021-12-01 18:30
MQTT just adds another layer and another point of failure. I was thinking of integrating this directly with HA since HA already supports media players.
Adding TTS support would be awesome, since we could now have inexpensive speakers throughout the house.

**Comment by kquinsland** [comment] 2021-12-01 18:58
> MQTT just adds another layer and another point of failure. I was thinking of integrating this directly with HA since HA already supports media players. Adding TTS support would be awesome, since we could now have inexpensive speakers throughout the house.

MQTT is pretty robust. I'd bet that - of all the various issues/problems people experience with HA - the MQTT broker is seldom the root cause.

I prefer MQTT over HA's native API because I have other systems that don't speak to HA directly via it's API that also need to monitor/react to data from sensors. I am not the only one that has setups like this.  It is _somewhat_ common for people to hack together 3-way switch like functionality using a few tasmota smart switches that communicate **directly** with one another over HTTP/MQTT.

Even if these other sensors and actuators _could_ integrate directly into HA via its HTTP api... the HA instance would become the SPOF. MQTT - unlike Home Assistant - was designed for deployments in a cluster or other topology where highly available / fault tolerant is paramount.

**Comment by rarroyo6** [comment] 2021-12-07 04:41
I'm not putting down MQTT, I'm very familiar with it and have used it several times in the past.
I'm just saying that the Media Player integration should not be tied to MQTT, it should be independent of the transport. Once a player can be defined in the ESPHome YAML, then the if data can get to it via MQTT or the API is indifferent.
I understand your use scenario, but HA is capable of supporting both MQTT and API at the same time, and since it already supports the Media Player directly but not through MQTT, it would just complicate things by adding another layer to the implementation.
Lets keep it simple, get it working, then add all the other enhancements afterwards.

**Comment by kquinsland** [comment] 2021-12-08 17:49
> I'm just saying that the Media Player integration should not be tied to MQTT, it should be independent of the transport. 

We're very much on the same page here :).  Unfortunately, there [does not appear to be _any_ way to announce a media player to HA via MQTT](https://www.home-assistant.io/docs/mqtt/discovery/). Alarm control panels are... but not media players :/.

My concern is that thins will _stay_ this way: media players are only programmatically available via HA API and not MQTT.

**Comment by brano1990** [comment] 2021-12-30 13:07
I would also like to use ESP on TTS

**Comment by magiva** [comment] 2022-03-06 08:57
esp32 is more than powerful enough to stream audio
there is a wish ticket created just like this https://github.com/esphome/feature-requests/issues/1421

**Comment by Blue-Beaker** [comment] 2022-04-03 14:09
At least add support for the media class, with custom media and template media. 
It can provide a friendly interface for controlling media players, the existing DF-Player component, even the ESP32 itself as a bluetooth audio receiver.

**Comment by nagyrobi** [comment] 2022-07-01 07:18
https://esphome.io/components/media_player/i2s_audio.html

**Comment by nagyrobi** [comment] 2022-07-01 07:26
https://github.com/esphome/feature-requests/issues/783

**Closed by nagyrobi** 2022-07-01 07:26 UTC
Labels: integration: media_player
