### ISSUE TITLE
ESP32C3 Not uploading to device 

### ISSUE THREAD

**Issue by jeggleston1981** [esphome/feature-requests#1307] opened 2021-07-20 12:56 UTC
**Describe the problem you have/What new integration you would like**

I have an ESP32c3 module from AI thinker, it is single-core and has a 160mhz cpu.
Can it work with ESPhome, please?
**Please describe your use case for this integration and alternatives you've tried:**

HomeESP at the moment can't upload to the module. Arduino IDE can upload sketches to the ESP32c3 DEV board and this is what I'm using it on at the moment it also works on the AI think module, I tried using the ESPhomeflasher with the dev version of esptool.py but it didn't work either, it did detect it as an ESP32c3, but that was all. The ESP32c3 is an exact replacement for the ESP8285 pin for pin but with bluetooth, 4MB flash and PWM, etc, so way better.
**Additional context**

**Comment by agners** [comment] 2021-07-21 09:52
Duplicate of #1217

**Closed by agners** 2021-07-21 09:52 UTC
