### ISSUE TITLE
Priority list for BSSID selection

### ISSUE THREAD

**Issue by erazor666** [esphome/feature-requests#162] opened 2019-04-07 13:45 UTC
**Describe the problem you have/What new integration you would like**
If this is possible with the underlying wifi libraries, would be nice to have a "priority list" with preferred BSSIDS. ESPs arent all that smart when selecting APs (at least not with my current setup that has a bit of overlap on 2.4ghz) I have a single SSID for them to connect that is available on multiple on multiple APs.

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by OttoWinter** [comment] 2019-04-07 13:46
Duplicate of https://github.com/esphome/feature-requests/issues/136

**Closed by OttoWinter** 2019-04-07 13:46 UTC
