### ISSUE TITLE
SPIFFS/SDCard support and FTP access

### ISSUE THREAD

**Issue by ogry** [esphome/feature-requests#982] opened 2020-11-05 20:12 UTC
Possibility of storing data in SPIFFS and being able to access it with an integrated FTP server

**Describe the problem you have/What new integration you would like**

Register data autonomously, save configuration files, custom components can read configuration details from files, html/css files for webserver (for non internet cases) ...

**Please describe your use case for this integration and alternatives you've tried:**

Integrating hundred of RF signals, storing data from sensors, saving last pic from esp32CAM...

**Additional context**

A simple way to create easily reconfigurable devices, the simplest autonomous signal recorder, ...

**Comment by nagyrobi** [comment] 2022-07-08 09:40
Duplicate of https://github.com/esphome/feature-requests/issues/513

**Closed by nagyrobi** 2022-07-08 09:40 UTC
Labels: Type: Communication Channel
