### ISSUE TITLE
Disable Status updates via MQTT for selected components

### ISSUE THREAD

**Issue by kellertobias** [esphome/feature-requests#514] opened 2019-12-01 04:57 UTC
**Describe the problem you have/What new integration you would like**
I am using around one hundred devices on a home control project. Each device sends status messages, when the relay or light status changed. sometimes this is not necessary and I want to disable it for given components (e.g. rgbw or monochromatic output)

**Please describe your use case for this integration and alternatives you've tried:**

My Idea would be to set the status topic to false to disable non explicit (e.g. status messages) mqtt messages sent from this device, while explicit (e.g. on_press mqtt.publish callbacks) will remain.

**Additional context**

**Comment by OttoWinter** [comment] 2019-12-03 13:46
Duplicate of https://github.com/esphome/feature-requests/issues/375

**Closed by OttoWinter** 2019-12-03 13:46 UTC
Labels: component: mqtt
