### ISSUE TITLE
Support for MAX44009 High range (0-188k) Lux Sensor

### ISSUE THREAD

**Issue by rradar** [esphome/feature-requests#238] opened 2019-05-20 20:16 UTC
**Describe the problem you have/What new integration you would like**

MAX44009 Support (i2c)

**Please describe your use case for this integration and alternatives you've tried:**

Measure lux outside and therefor need a high range >100k for direct sun light.

No integration right now supports to measure sun with esphome :sun_with_face: :disappointed: 
**Additional context**

https://datasheets.maximintegrated.com/en/ds/MAX44009.pdf
https://github.com/dantudose/MAX44009

**Comment by Esiravegna** [comment] 2019-06-17 17:30
Maybe this code could save you some time.
https://github.com/esphome/feature-requests/issues/29#issuecomment-447176550

**Comment by OttoWinter** [comment] 2019-06-17 17:56
@Esiravegna Thanks for the link

Marking this as duplicate of https://github.com/esphome/feature-requests/issues/29

**Closed by OttoWinter** 2019-06-17 17:56 UTC
Labels: Type: I2C, Type: Illuminance
