### ISSUE TITLE
MH-Z19 / MH-Z19b detection range

### ISSUE THREAD

**Issue by randompee** [esphome/feature-requests#995] opened 2020-11-16 13:33 UTC
**Describe the problem you have/What new integration you would like**

The MH-Z19b can be configured for a CO2 detection range of 0-2000ppm or 0-5000ppm. Please add this, with a default of 2000.
**Please describe your use case for this integration and alternatives you've tried:**

In ESPhome this sensor will mostly be deployed in living rooms, where approx. 1000 ppm CO2 should not be exceeded. So, a measuring range up to 2000 ppm maximum is appropriate, especially as the accuracy also seems to be better for a smaller range.
**Additional context**

The manufacturers product manual gives the relevant commands:

- set 0~2000ppm detection range, send command: FF 01 99 00 00 00 07 D0 8F
- set 0~10000ppm detection range, send command: FF 01 99 00 00 00 27 10 2F

These commands are valid also for the elder MH-Z19.

 !-- LEAVE THIS LINE AS-IS AND DON'T DELETE IT, OTHERWISE THE FEATURE REQUEST WILL BE CLOSED AUTOMATICALLY. -->

**Comment by evils** [comment] 2022-12-14 14:12
duplicate of #438?

**Closed** 2022-12-14 14:38 UTC
Labels: integration: mhz19
