### ISSUE TITLE
Script parameters support

### ISSUE THREAD

**Issue by Nardol** [esphome/feature-requests#1523] opened 2021-11-24 15:43 UTC
**Describe the problem you have/What new integration you would like**

Home Assistant provide the ability to add parameters to scripts.
Actualy, it is not the case in ESPHome.
Providing this also in ESPHome could allow more flexibility for scripts.

**Please describe your use case for this integration and alternatives you've tried:**

I have some Switchbot meters I get temperature, hydrometry, battery level and RSSI.
For now, I have to repeat the code to get information for each device.

**Additional context**

With script parameters, I could use a script where I could use one for each sensor ID to set and call it for each time one of the MAC address advertise itself using BLE.

**Comment by matthewfallshaw** [comment] 2022-08-27 06:14
Duplicate of #241

**Closed** 2022-08-27 06:28 UTC
Labels: Type: Automation
