### ISSUE TITLE
Esphome server

### ISSUE THREAD

**Issue by hpirila** [esphome/feature-requests#245] opened 2019-05-26 07:40 UTC
**Describe the problem you have/What new integration you would like**

Esphome is the best thing in home automation scene I have seen. Really amazing stuff. So I don't really have any problem with it.

But I would like to see something like ESP Home Server where similar yaml file is used on server side and that server runs example on ESP32. It would then communicate with ESP Home equipments and do simple automation tasks. So very similar than Home Assistant does today but being more light weight and having less features. Even the web server not that important.

**Please describe your use case for this integration and alternatives you've tried:**

This is just an idea.

**Additional context**

**Comment by OttoWinter** [comment] 2019-05-26 08:26
Duplicate of https://github.com/esphome/feature-requests/issues/46

**Closed by OttoWinter** 2019-05-26 08:26 UTC
