### ISSUE TITLE
Current limit for Addressable Lights / FastLED / NeoPixelBus

### ISSUE THREAD

**Issue by it-guy92** [esphome/feature-requests#1666] opened 2022-03-07 07:47 UTC
**Describe the problem you have/What new integration you would like**
It would be great if someone can implement a current limit for addressable lights like WS2812, SK6812,...

**Please describe your use case for this integration and alternatives you've tried:**
I am designing a Smart Home PCB for my Motorhome. This PCB contains a ESP32 and a 5V Buck converter. I want to limit this Buck converter to 20A. But I operate about 500 SK6812 LEDs which consumes at full power 25A. On WLED you can specify a current limit for this case. On WLED, if i try to push the brightness to far, it's brightness is limited and my Powersource wont be overloaded. 
On other words: If i try to turn to much leds on, the LEDs should be dimmed to prevent overload on my Power Supply.

I think there is a [function](https://github.com/Makuna/NeoPixelBus/issues/310) for this.

**Comment by nagyrobi** [comment] 2022-07-08 10:32
Duplicate of https://github.com/esphome/feature-requests/issues/712

**Closed by nagyrobi** 2022-07-08 10:32 UTC
