### ISSUE TITLE
Display User created Folders in Dashboard

### ISSUE THREAD

**Issue by benquan** [esphome/feature-requests#1821] opened 2022-08-07 14:46 UTC
**Describe the problem you have/What new integration you would like**

User created folders do not display on the dashboard. They should appear on the dashboard to allow users to navigate in these files and allow editing files within.

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by lcavalli** [comment] 2022-09-02 20:42
Duplicate of #867?

**Comment by nagyrobi** [comment] 2022-09-03 05:15
Yes, thank you.

**Closed by nagyrobi** 2022-09-03 05:15 UTC
Labels: Project: Dashboard
