### ISSUE TITLE
Make website more colour blind friendly

### ISSUE THREAD

**Issue by kloggy** [esphome/feature-requests#1263] opened 2021-06-17 10:35 UTC
**Describe the problem you have/What new integration you would like**

Please change the red and green top border indicating on or off line to different colours.

The current colours are extremely colour blind unfriendly.

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by wtadler** [comment] 2021-06-22 01:07
I'm not colorblind myself, but was just thinking the same. It's subtle even for non-color blind users. Indicators that use both an icon and a color (e.g., ❌ and ✅) would be better.

To illustrate the problem, here's an ESPHome dashboard...
<img width="1286" alt="Screen Shot 2021-06-21 at 8 56 53 PM" src="https://user-images.githubusercontent.com/6721528/122846472-e2cdc280-d2d3-11eb-900a-135920a1aa6d.png">

...and here's that same dashboard run through [this color blindness simulator](https://www.color-blindness.com/coblis-color-blindness-simulator/) for deuteranopia. Good luck quickly determining which devices are connected!
![download (1)](https://user-images.githubusercontent.com/6721528/122846807-9df65b80-d2d4-11eb-9b53-df2a45fd289f.png)


Red-green colorblindess is very common.

**Comment by jesserockz** [comment] 2021-06-22 03:43
Duplicate of #890

**Closed by jesserockz** 2021-06-22 03:43 UTC
