### ISSUE TITLE
GPS Location

### ISSUE THREAD

**Issue by Puntoboy** [esphome/feature-requests#781] opened 2020-06-24 18:21 UTC
**Describe the problem you have/What new integration you would like**

See previous request. https://github.com/esphome/feature-requests/issues/164 

**Please describe your use case for this integration and alternatives you've tried:**

GPS tracker

**Additional context**

**Comment by rradar** [comment] 2020-07-02 14:23
I close this as a duplicate of #622 which includes the request to support location

**Closed by rradar** 2020-07-02 14:23 UTC
