### ISSUE TITLE
Max Current option for Light component

### ISSUE THREAD

**Issue by to4ko** [esphome/feature-requests#1007] opened 2020-11-20 09:06 UTC
**Describe the problem you have/What new integration you would like**

It would be very useful to have max_current option for light component. The idea - to have limiting factor by specifying power supply data. 

**Please describe your use case for this integration and alternatives you've tried:**

Connecting long "heavy" led strip to power supply with low current specs and turning n the strip to full brightness. Could lead to dangerous situation.
**Additional context**

**Comment by nagyrobi** [comment] 2022-07-08 10:32
Duplicate of https://github.com/esphome/feature-requests/issues/712

**Closed by nagyrobi** 2022-07-08 10:32 UTC
Labels: integration: light
