### ISSUE TITLE
modbus_controller climate

### ISSUE THREAD

**Issue by krismaddens** [esphome/feature-requests#2751] opened 2024-06-08 10:30 UTC
**Describe the problem you have/What new integration you would like**
 A modbus_controller climate that can be linked  to a modbus address where the assigned modbusregisters are updated like any other climate entity. 

**Please describe your use case for this integration and alternatives you've tried:**
 In modbus_controller we have the possibility to create sensors, switch, number, .... that can be linked  to a modbus address but there is no climate for modbus_controller. in fact it is a combination of sensor, number for target temperature, sellect for mode.  that would be nice if any temperature controller or device with a temperature controller that has rs485 modbus connectivity to be controlled by esphome. that way it would work like the modbus climate in HA where the assigned modbusregisters are updated like any other climate entity https://www.home-assistant.io/integrations/modbus/  

**Additional context**
I know that if it is just only a temperature controling device we can use the HA modbus climate as a good solution but id the device has more than just a temperature controler but also has controllers for other parameters like pH, orp, dosing,... it would be nice to create a esphome based gateway so there is no need for creating all the stuf in HA configuration.yaml   but instead have all the entities available from the esphome integration

**Comment by nagyrobi** [comment] 2024-06-08 13:38
Duplicate of https://github.com/esphome/feature-requests/issues/2752

Let's keep discussion in a single topic.

**Closed by nagyrobi** 2024-06-08 13:38 UTC
