### ISSUE TITLE
Adding support for SPI on BME280

### ISSUE THREAD

**Issue by DamianBroj** [esphome/feature-requests#1436] opened 2021-09-27 21:31 UTC
**Describe the problem you have/What new integration you would like**

I would like to be able to connect multiple BME280 sensors to SPI on ESP8266
**Please describe your use case for this integration and alternatives you've tried:**

Currently there is support for I2C implemented, but this sensor works on SPI as well
**Additional context**

**Comment by tomlut** [comment] 2022-02-06 00:21
This is needed to enable more than two BME280s to be connected to an ESP8266.

**Comment by nagyrobi** [comment] 2022-07-07 10:08
Duplicate of https://github.com/esphome/feature-requests/issues/1321

**Closed by nagyrobi** 2022-07-07 10:08 UTC
Labels: integration: bme280
