### ISSUE TITLE
Option to identify a device as several devices

### ISSUE THREAD

**Issue by dala318** [esphome/feature-requests#2669] opened 2024-04-01 06:14 UTC
**Describe the problem you have/What new integration you would like**

I have a Modbus controller that reads several Modbus slave devices. Each slave with its own set of parameters, all identified as unique entities.
For readability in HA it would be neat if I could set some property per entity originating from same physical device in Esphome config that would generate a unique device in HA per such property.

**Please describe your use case for this integration and alternatives you've tried:**

I looked into the HA integration code quickly and could only find that the device was identified by its mac-address. Should be plenty more properties in that class to set uniquely.

**Additional context**

**Comment by nagyrobi** [comment] 2024-04-02 08:51
Duplicate of https://github.com/esphome/feature-requests/issues/1335

**Closed by nagyrobi** 2024-04-02 08:51 UTC
