### ISSUE TITLE
ODB2 to UART

### ISSUE THREAD

**Issue by iotemylabs** [esphome/feature-requests#1023] opened 2020-11-30 01:30 UTC
**Describe the problem you have/What new integration you would like**

Automatic ODB2 reader and the integration died off this year, and I have been looking for ways I can integrate my car into Home Assistant, and since I wasn't aware of useful alternatives, I think with a combination of the connected binary sensor, gps component, even backup small data to home assistant away from your home LAN.

**Please describe your use case for this integration and alternatives you've tried:**

I have tried my best to integrate using the custom UART sensor / binary sensor / switch, but it has not been the most straightforward. The use case is for Odometer reading, fuel level, latest trip recording, even for a binary sensor for if the engine light is on, and maybe a bank of error codes it outputs.

**Additional context**

https://www.sparkfun.com/products/9555

**Comment by nagyrobi** [comment] 2022-07-08 10:22
Duplicate of https://github.com/esphome/feature-requests/issues/935

**Closed by nagyrobi** 2022-07-08 10:22 UTC
