### ISSUE TITLE
Add ESPNOW gateway in ESPhome

### ISSUE THREAD

**Issue by phpphph** [esphome/feature-requests#1828] opened 2022-08-13 05:59 UTC
![mmexport1660370039275](https://user-images.githubusercontent.com/70796642/184470732-f1c5ec74-fae0-49f1-91a5-a2f93cff042c.png)
Add ESPNOW gateway in ESPhome
Use two esp32 modules.A dedicated ESPNOW protocol networking transceiver,The other one is used to forward to WIFI。I can only design hardware, not write software. sorry！If you think this idea is convenient to operate。Please help us achieve it. Thank you very much!

**Comment by nagyrobi** [comment] 2022-08-13 06:12
Duplicate of https://github.com/esphome/feature-requests/issues/275

**Closed by nagyrobi** 2022-08-13 06:12 UTC
Labels: Type: Communication Channel

**Comment by phpphph** [comment] 2022-08-13 07:00
> #275的副本[](https://github.com/esphome/feature-requests/issues/275)

您有何见解呢
