### ISSUE TITLE
EZO sensors pH and EC Calibration

### ISSUE THREAD

**Issue by peripoccu** [esphome/feature-requests#1200] opened 2021-04-30 13:06 UTC
**Describe the problem you have/What new integration you would like**

Missing feature to do the pH and EC calibrations

**Please describe your use case for this integration and alternatives you've tried:**

I'm using Atlas Scientific hydroponic kit, it uses ESP8266 and EZO sensors, everything works great, but it's impossible to perform the calibrations. This operation must be regularly (at least once per month) and right now the only way to do it it's to flash another firmware, do the calibration and flash the new firmware

**Additional context**

https://github.com/Atlas-Scientific/Ezo_I2c_lib/blob/master/Examples/IOT_kits/hydroponics_kit/hydroponics_kit.ino

https://atlas-scientific.com/files/Wi-Fi-Hydroponics-kit-setup-guide.pdf (Step 8)

**Comment by nagyrobi** [comment] 2022-07-08 11:05
Duplicate of https://github.com/esphome/feature-requests/issues/1179

**Closed by nagyrobi** 2022-07-08 11:05 UTC
