### ISSUE TITLE
Add last 4 characters of chip MAC address to name/ap

### ISSUE THREAD

**Issue by carlos-sarmiento** [esphome/feature-requests#191] opened 2019-04-24 17:22 UTC
**Describe the problem you have/What new integration you would like**
I'm migrating all my lightbulbs to sonoff B1s and I'm currently running into the issue that I must have a separate template for each lightbulb, in which the only thing I'm changing is the name of the device and the fallback AP. 

It would be great if ESPHome could read the MAC address of the chip before compiling the code and append it to the end of the name, (and component ids, etc.) of the device before flashing the firmware. I am aware everything is hardcoded on the actual firmware, so I'm not asking for it to be updatable after flashing. Only that a unique identifier for the chip (MAC address) can be used on identifiers.

That way people could use a single file to flash a bunch of devices without having to worry about having the right yaml file for the right device. Later, using Home Assistant Entities control panel, the entities could be renamed to something more appropriate.

**Please describe your use case for this integration and alternatives you've tried:**
Right now I'm using a bash script to take a template file and append a random number to the id's before flashing the chip. The issue with this approach is that I still have to make sure I'm using the right file for the right physical chip.

**Additional context**

**Comment by OttoWinter** [comment] 2019-04-24 19:50
Duplicate of https://github.com/esphome/esphome/issues/278

**Closed by OttoWinter** 2019-04-24 19:50 UTC
