### ISSUE TITLE
Add NRF24L01

### ISSUE THREAD

**Issue by leech001** [esphome/feature-requests#894] opened 2020-09-13 13:15 UTC
**Describe the problem you have/What new integration you would like**
Please add NRF24L01 to ESPHOME

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by randybb** [comment] 2020-09-13 16:38
Duplicate of #45

**Closed by randybb** 2020-09-13 16:38 UTC

**Comment by leech001** [comment] 2020-09-14 10:06
Sorry, just the search works disgustingly. I didn't find the search query "NRF24" on it.
