### ISSUE TITLE
Zigbee and Thread in ESP home. Pretty sure the ESP32-C6 (at least) has Zigbee and thread/matter radios. It'd be very nice if they could work with ESPhome and a Zigbee or Matter dongle.

### ISSUE THREAD

**Issue by eerke2021** [esphome/feature-requests#2426] opened 2023-10-11 01:02 UTC
**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by JarekToro** [comment] 2023-10-15 13:51
Also ESP32-H2

**Comment by fridtjof** [comment] 2023-10-19 12:31
#1397

**Comment by nagyrobi** [comment] 2023-10-19 14:12
Duplicate of https://github.com/esphome/feature-requests/issues/1397 https://github.com/esphome/feature-requests/issues/1430

**Closed by nagyrobi** 2023-10-19 14:12 UTC
