### ISSUE TITLE
Feature request - reading data from a Xiaomi Bluetooth Kettle with an ESP32 board

### ISSUE THREAD

**Issue by jascdk** [esphome/feature-requests#587] opened 2020-02-02 23:04 UTC
**Describe the problem you have/What new integration you would like**
Connection to a Xiaomi Bluetooth kettle for boiling water

**Please describe your use case for this integration and alternatives you've tried:**
Hi i have a Xiaomi Kettle "Mikettle" which has BLE inside. Would it be possible to integrate it as the other Xiaomi products with an esp32 board as a hub? There are some resources / libraries here on GitHub

**Additional context**

**Comment by jascdk** [comment] 2020-02-02 23:06
https://github.com/drndos/mikettle

**Comment by n4ts** [comment] 2020-02-05 10:36
The same feature request is here:
https://github.com/esphome/feature-requests/issues/517

Please add "up" emoji there

**Comment by glmnet** [comment] 2020-02-07 19:06
duplicate of #517

**Closed by glmnet** 2020-02-07 19:06 UTC
