### ISSUE TITLE
Support for Adafruit VEML7700 light sensor.

### ISSUE THREAD

**Issue by marcddd** [esphome/feature-requests#1915] opened 2022-10-13 08:17 UTC
**Describe the problem you have/What new integration you would like**

Support for light sensor adafruit veml7700. 

**Please describe your use case for this integration and alternatives you've tried:**

The sensor platform is jot supported. 

**Additional context**

**Comment by nagyrobi** [comment] 2022-10-13 08:36
Duplicate of https://github.com/esphome/feature-requests/issues/218

**Closed by nagyrobi** 2022-10-13 08:36 UTC
