### ISSUE TITLE
set WIFI ssid&password using webserver or using smartconfig,or airkiss

### ISSUE THREAD

**Issue by witsoft001** [esphome/feature-requests#286] opened 2019-06-17 10:10 UTC
**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by OttoWinter** [comment] 2019-06-17 13:00
Duplicate of https://github.com/esphome/feature-requests/issues/86

**Closed by OttoWinter** 2019-06-17 13:00 UTC
