### ISSUE TITLE
Support for HUB75 LED Panel Matrix Display

### ISSUE THREAD

**Issue by ustunsoz** [esphome/feature-requests#2291] opened 2023-06-28 08:17 UTC
**Describe the problem you have/What new integration you would like**
Please include device RGB-Matrix-P2.5 for ESPhome to enable to control LED Panel Matrix Display 

**Please describe your use case for this integration and alternatives you've tried:**
 LED Matrix Displays are essential to use together with home assistant 

**Additional context**
 Necessary description and libraries available here https://www.waveshare.com/wiki/RGB-Matrix-P2.5-64x64  
64x64 specifies panel sizes please consider to make işt available for 128x64

**Comment by nagyrobi** [comment] 2023-06-28 08:19
Duplicate of https://github.com/esphome/feature-requests/issues/1967

**Closed by nagyrobi** 2023-06-28 08:19 UTC

**Comment by nagyrobi** [comment] 2023-06-28 08:21
Also see https://github.com/TillFleisch/ESPHome-HUB75-MatrixDisplayWrapper
