### ISSUE TITLE
ESPHome native API: active connection establishment (from device to Home Assistant)

### ISSUE THREAD

**Issue by leo-b** [esphome/feature-requests#2746] opened 2024-06-05 16:52 UTC
**Describe the problem you have/What new integration you would like**

Currently ESPHome API connections are initiated by Home Assistant: The ESPHome device listens and the HA server establishes a TCP connection to the device. This works fine in local setups.

However, if ESPHome devices and HA server are in different networks and maybe the ESPHome devices are behind a NAT, initiating a connection from the HA server is sometimes not possible.

**Please describe your use case for this integration and alternatives you've tried:**

My primary use case are decentralized IOT devices that are behind some kind of NAT (maybe ISP carrier grade NAT).

I know that using the MQTT client could be a way to solve this problem. But as you know, the [ESPHome native API has many advantages](https://esphome.io/components/api.html#advantages-over-mqtt). ;-)

**Additional context**

**Comment by nagyrobi** [comment] 2024-06-05 17:25
Duplicate of https://github.com/esphome/feature-requests/issues/46

**Closed by nagyrobi** 2024-06-05 17:25 UTC
