### ISSUE TITLE
ESP32_CAM - Add RTSP server?

### ISSUE THREAD

**Issue by keith721** [esphome/feature-requests#284] opened 2019-06-15 13:45 UTC
**Describe the problem you have/What new integration you would like**
Wondering if this [geeksville RTSP server](https://github.com/geeksville/Micro-RTSP) could be incorporated into ESP32_CAM ?

**Please describe your use case for this integration and alternatives you've tried:**
Current component provides JPEG snapshots.  Would like to enable an RTSP stream

**Additional context**

If a similar feature already exists, I could not find it.  Thanks for listening!

**Comment by OttoWinter** [comment] 2019-06-15 13:51
Duplicate of #156

**Closed by OttoWinter** 2019-06-15 13:51 UTC
