### ISSUE TITLE
current_color in AddressableLambdaLightEffect

### ISSUE THREAD

**Issue by Roncoroni** [esphome/feature-requests#224] opened 2019-05-11 19:40 UTC
**Describe the problem you have/What new integration you would like**

It would be nice to access the current color of a Neopixelbus Light in a lambda effect.
The `current_color` is available in the function `apply` but will not provided to the call to the lambda.

**Please describe your use case for this integration and alternatives you've tried:**

I want to write multiple complex animations which use the actual color.
Until now, if i change the color of the stripe, the animation has no possibility to get this update.

**Additional context**

nope

**Comment by OttoWinter** [comment] 2019-05-12 11:04
You can always check the current color yourself with `id(my_light).get_current_values()`

**Comment by Roncoroni** [comment] 2019-05-20 14:25
ok, thanks for this hint. It works for me.

But i think, to provide the parameter current_value to the lambda is much clearer and easer reusable.

**Comment by OttoWinter** [comment] 2019-05-25 19:14
Yeah but the problem is that it cannot be added easily - the function can only accept one argument, and that is `it`.

Closing as already possible and not easy to add.

**Closed by OttoWinter** 2019-05-25 19:14 UTC
Labels: component: light
