### ISSUE TITLE
OTA firmware upload option on next connection. 

### ISSUE THREAD

**Issue by markusg1234** [esphome/feature-requests#1203] opened 2021-05-01 13:40 UTC
**Describe the problem you have/What new integration you would like**
When using deep sleep wakeup it is harder to update firmware if run duration is small. It would be great if an upload can be delayed, then the next time the device wakes up it will update automatically. 

**Please describe your use case for this integration and alternatives you've tried:**
 Normally I wake up the ESP via an input or a reboot. This is harder if the device is not easily accessible 

**Additional context**

**Comment by nagyrobi** [comment] 2022-07-08 11:04
Duplicate of https://github.com/esphome/feature-requests/issues/112

**Closed by nagyrobi** 2022-07-08 11:04 UTC
Labels: integration: ota
