### ISSUE TITLE
Add Tilt Functions to Template Cover or New Tilt Cover

### ISSUE THREAD

**Issue by mtl010957** [esphome/feature-requests#90] opened 2019-02-28 19:57 UTC
**Describe the problem you have/What new integration you would like**

The current template cover component only handles the simplest cover functionality of open, close and stop. HA Covers have significantly more capability, including Tilt features (to handle setting the tilt angle of window blinds). I would like to have the tilt features available in the ESPHome cover components as well.

**Please describe your use case for this integration and alternatives you've tried:**

Having a cover with tilt features, specifically set_tilt_position and current_tilt_position, along with settings for tilt_min, tilt_max, tilt_opened_value and tilt_closed_value, I can put together a tilting cover with a PWM output to drive a servo to move the window blinds.

**Additional context**

The min_power setting added to output enables driving the servo, I just need the tilt features added to cover to have the complete capability without any custom components or tricky workarounds. I have a working setup now using an MQTT Sensor to receive the tilt commands from HA but it's kludgy and doesn't support discovery. I'll be happy to attempt a solution on this, please let me know if extending template cover is best or creating a new tilting cover is better.

**Comment by OttoWinter** [comment] 2019-03-11 20:24
Duplicate of https://github.com/esphome/feature-requests/issues/42

**Closed by OttoWinter** 2019-03-11 20:24 UTC
Labels: component: cover
